/**
 * Professional icon mapping for calculators.
 * Uses Lucide icons only - no emoji.
 */
import {
  Activity,
  ArrowUpDown,
  Award,
  BadgeCheck,
  Banknote,
  BookOpen,
  BookOpenCheck,
  Box,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Cake,
  Calculator as CalculatorIcon,
  Car,
  ChartCandlestick,
  ChartNoAxesCombined,
  Circle,
  CircleDot,
  ClipboardCheck,
  Clock,
  CreditCard,
  Dices,
  Divide,
  Dumbbell,
  Fence,
  FlaskConical,
  Flame,
  Footprints,
  Gauge,
  GitCompare,
  GraduationCap,
  Grid,
  HandCoins,
  HardHat,
  HeartPulse,
  Home,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Map,
  MessageCircle,
  Mountain,
  Move,
  Paintbrush,
  Percent,
  PersonStanding,
  PiggyBank,
  Plug,
  Receipt,
  Ruler,
  Scale,
  Scan,
  Sigma,
  Square,
  Sun,
  Target,
  Thermometer,
  TrendingDown,
  TrendingUp,
  Type,
  Utensils,
  Wallet,
  WalletCards,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Map calculator id → Lucide icon
export const calculatorIcons: Record<string, LucideIcon> = {
  // Finance
  mortgage: Home,
  loan: Landmark,
  emi: CreditCard,
  "compound-interest": ChartNoAxesCombined,
  "simple-interest": Percent,
  sip: TrendingUp,
  investment: TrendingUp,
  gst: Receipt,
  percentage: Percent,
  "percentage-change": TrendingUp,
  "home-loan-emi": Home,
  "auto-loan": Car,
  "car-loan-emi": Car,
  savings: PiggyBank,
  retirement: Sun,
  "credit-card-payoff": CreditCard,
  "debt-payoff": Banknote,
  dti: Percent,
  roi: TrendingUp,
  apr: Percent,
  inflation: TrendingUp,
  tip: HandCoins,
  "sales-tax": Receipt,
  "currency-converter": WalletCards,
  ppf: Wallet,
  cagr: TrendingUp,
  nps: MessageCircle,
  gratuity: BadgeCheck,
  hra: Home,
  epf: Wallet,
  "income-tax": Receipt,
  salary: WalletCards,
  "personal-loan-emi": Banknote,
  // Construction
  area: Square,
  volume: Box,
  concrete: Layers,
  "square-footage": Ruler,
  roofing: Home,
  tile: Grid,
  gravel: Mountain,
  mulch: Leaf,
  paint: Paintbrush,
  flooring: LayoutGrid,
  fence: Fence,
  stair: ArrowUpDown,
  // Science
  "ohms-law": Zap,
  "voltage-drop": TrendingDown,
  power: Zap,
  resistor: Circle,
  "electrical-energy": Plug,
  density: Scale,
  speed: Gauge,
  distance: Map,
  force: Move,
  pressure: Gauge,
  "temperature-converter": Thermometer,
  // Math
  discount: Percent,
  fraction: Divide,
  ratio: Scale,
  average: Sigma,
  rounding: CircleDot,
  "scientific-notation": Sigma,
  "number-to-words": Type,
  "random-number": Dices,
  "fraction-to-decimal": Divide,
  "decimal-to-fraction": Divide,
  "unit-converter": Ruler,
  standard: CalculatorIcon,
  scientific: Sigma,

  // Education
  cgpa: GraduationCap,
  gpa: GraduationCap,
  grade: BadgeCheck,
  "final-grade": Award,
  "weighted-grade": Scale,
  attendance: CalendarCheck,
  "marks-percentage": ClipboardCheck,
  "exam-percentage": BookOpenCheck,
  "semester-gpa": BookOpen,
  marks: ClipboardCheck,

  // Health
  bmi: HeartPulse,
  bmr: Activity,
  calorie: Flame,
  tdee: Gauge,
  "body-fat": Scan,
  "ideal-weight": Scale,
  "healthy-weight": PersonStanding,
  macro: Utensils,
  protein: Dumbbell,
  pace: Footprints,
  "pregnancy-due-date": HeartPulse,
  "pregnancy-weight-gain": Scale,
  ovulation: Calendar,
  period: Calendar,
  "one-rep-max": Dumbbell,
  "target-heart-rate": HeartPulse,

  // Date & Time
  age: Calendar,
  date: CalendarDays,
  "date-difference": GitCompare,
  "days-between-dates": CalendarRange,
  "time-duration": Clock,
  birthday: Cake,
  "days-until-birthday": Cake,
  "business-days": Briefcase,
  "weeks-between-dates": CalendarRange,
  "months-between-dates": CalendarClock,
};

// Category icon mapping
export const categoryIcons: Record<string, LucideIcon> = {
  math: CalculatorIcon,
  finance: Wallet,
  education: GraduationCap,
  health: HeartPulse,
  construction: HardHat,
  science: FlaskConical,
  "date-time": Calendar,
};

export function getCalculatorIcon(id: string): LucideIcon {
  return calculatorIcons[id] ?? CalculatorIcon;
}

export function getCategoryIcon(id: string): LucideIcon {
  return categoryIcons[id] ?? CalculatorIcon;
}